### ISSUE TITLE
Read block operation failed 

### ISSUE THREAD

**Issue by msubirana** [kensung-lab/INSurVeyor#6]
Hi,

I've been trying INSurVeyor, I installed and as the doc comments I added MC tag using picard. When I tried INSurVeyor with a subset bam I got this error:

```
[E::bgzf_read] Read block operation failed with error 2 after 0 of 4 bytes
Traceback (most recent call last):
  File "/home/msubirana/Documents/phd/repos/cancer-sv-pipeline/install_dir/INSurVeyor/surveyor.py", line 102, in <module>
    for read in bam_file.fetch(contig=chr, start=pos, end=pos+10000):
  File "pysam/libcalignmentfile.pyx", line 2086, in pysam.libcalignmentfile.IteratorRowRegion.__next__
OSError: truncated file
```

Any ideas? Thanks!

**Comment by msubirana** [comment]
I solved regenerating the bai index after the FixMateInformation
